server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: xi-api-interface
          uri: http://localhost:8081
          predicates:
            - Path=/api/**
  redis:
    port: 6379
    host: localhost
    database: 0
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  consumer:
    timeout: 20000  # 消费者全局超时时间
  provider:
    timeout: 20000  # 提供者全局超时时间
  application:
    qosEnable: false
    enable-file-cache: false
    name: dubbo-gateway-customer
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848