spring:
  profiles:
    active: dev
  application:
    name: xi-api-backend
  # todo 修改为自己的数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xi_api
    username: root
    password: root
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0

server:
  port: 7529
  address: 0.0.0.0
  servlet:
    context-path: /api
    session:
      cookie:
        # 一周
        max-age: 604800
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# xi-api-SDK 配置，如需使用自己的网关host需修改
qi:
  api:
    client:
      # 本地测试网关地址
      host: http://localhost:8090/api

# 阿里云对象存储
aliyun:
  oss:
    file:
      endpoint:
      keyid:
      keysecret:
      bucketname:


dubbo:
  consumer:
    timeout: 20000  # 消费者全局超时时间
  provider:
    timeout: 20000  # 提供者全局超时时间
  application:
    enable-file-cache: false
    name: dubbo-backend-provider

  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    # todo 线上修改为服务器内网地址，参考nacos启动后的链接
    address: nacos://localhost:8848

ai:
  apiKey: xxx