server:
  port: 8081
  servlet:
    context-path: /api
spring:
  profiles:
    active: dev
  mvc:
    path match:
      matching-strategy: ant_path_matcher

dubbo:
  consumer:
    timeout: 20000  # 消费者全局超时时间
  provider:
    timeout: 20000  # 提供者全局超时时间
  application:
    qosEnable: false
    enable-file-cache: false
    name: dubbo-interface-customer
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848

xi:
  api:
    client:
      access-key:
      secret-key:

